---
- name: Install Apache and starts the service
  hosts: webserver
  tasks:
    - name: 1) Install the required package
      yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: latest

    - name: 2) Start the service
      service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"

    - name: 3) Open the service with firewall
      firewalld:
        service: "{{ ansible_local.custom.general.fwsvc }}"
        permanent: yes
        immediate: yes
        state: enabled
