---
- name: Uninstall and stop Apache HTTPD
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    ##########################
    # 1) 방화벽 포트 제거   - "{{ ansible_local.custom.general.fwsvc }}"
    # 2) 서비스 종료        - "{{ ansible_local.custom.general.service }}"
    # 3) 패키지 삭제        - "{{ ansible_local.custom.general.package }}"
    # 4) 사용자 정의 팩트 삭제  - /etc/ansible/facts.d/
    ##########################
    # 1) 방화벽 포트 제거   - "{{ ansible_local.custom.general.fwsvc }}"
    - name: 1) 방화벽 포트 제거 - "{{ ansible_local.custom.general.fwsvc }}"
      ansible.posix.firewalld:
        service: "{{ ansible_local.custom.general.fwsvc }}"
        permanent: true
        immediate: true
        state: disabled
    
    # 2) 서비스 종료        - "{{ ansible_local.custom.general.service }}"
    - name: 2) 서비스 종료 - "{{ ansible_local.custom.general.service }}"
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - "{{ ansible_local.custom.general.service }}"
        - firewalld

    # 3) 패키지 삭제        - "{{ ansible_local.custom.general.package }}"
    - name: 3) 패키지 삭제 - "{{ ansible_local.custom.general.package }}"
      ansible.builtin.dnf:
        name: "{{ ansible_local.custom.general.package }}"
        state: absent

    # 4) 사용자 정의 팩트 삭제  - /etc/ansible/facts.d/
    - name: 4) 사용자 정의 팩트 삭제 - /etc/ansible/facts.d/
      ansible.builtin.file:
        path: /etc/ansible/facts.d/
        state: absent
