---
- name: Install remote facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: 1) Create the remote directory
      file:
        state: directory
        recurse: true
        path: "{{ remote_dir }}"

    - name: 2) Install the new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
