---
- name: 0) 모든 관리 대상 호스트 전원 끄기
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) 전원 끄기
      community.general.shutdown:
        delay: 0
      ignore_errors: true    # 이미 꺼진 서버에 대해 에러표시 X

- name: 1) [제어노드] 전원 끄기
  hosts: localhost
  gather_facts: false
  tasks:
    - name: 1) 전원 끄기
      ansible.posix.at:
        command: shutdown
        count: 1
        units: minutes
      ignore_errors: true
