---
- name: 하드웨어 보고서 작성
  hosts: all
  become: true
  gather_facts: true
  vars:
    hwreportfile: /root/hwreport.txt
  tasks:
    ##########################
    # 1) 파일 배포
    # 2) 파일 작성
    # 3) 파일 수집
    ##########################
    # 1) 파일 배포
    # * (localhost) files/hwreport.txt -> (ansible1~4) /root/hwreport.txt
    - name: 1) 파일 배포 - files/hwreport.txt
      ansible.builtin.copy:
        src: files/hwreport.txt
        dest: /root/hwreport.txt
        owner: root
        group: root
        mode: '0600'

    # 2) 파일 작성
    # * INVENTORY_HOSTNAME
    # * TOTAL_MEM
    # * BIOS_VER
    # * SDA_SIZE
    - name: 2) 파일 작성 - INVENTORY_HOSTNAME
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'inventoryhostname'
        replace: "{{ inventory_hostname }}"
  
    - name: 2) 파일 작성 - TOTAL_MEM
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'totalmem'
        replace: "{{ ansible_memtotal_mb }}"

    - name: 2) 파일 작성 - BIOS_VER
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'biosversion'
        replace: "{{ ansible_bios_version }}"

    - name: 2) 파일 작성 - SDA_SIZE
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'sdasize'
        replace: "{{ ansible_devices.sda.size }}"

    # 3) 파일 수집
    # * /root/hwreport.txt -> results/*
    - name: 3) 파일 수집
      ansible.builtin.fetch:
        src: /root/hwreport.txt
        dest: results/{{ inventory_hostname }}-hwreport.txt
        flat: true
