---
- name: Restore use-vhost-role.yml
  hosts: all
  # roles:
  #   - { role: rollbacksvc, fw_rules: [dhcpv6-client] }
    # 여기서 명시하면 순서를 정할 수 없음
    # 모듈 형식을 사용하는 것을 권장
  tasks:
    - name: Role Test
      ansible.builtin.include_role:   # 이 방법을 추천
        name: rollbacksvc
      # vars:   # 변수를 vars/main.yml 파일이 아니라 여기서 지정할 수도 있음
      #   fw_rules:
      #     - http
      #     - https
      vars:
        web_files:
          - /etc/httpd/conf.d/vhost.conf
          - /var/www/html/index.html
          - /var/www/vhosts


