---
- name: Restore playbook.yml
  hosts: databases
  gather_facts: false
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: 1) 서비스 중지 - "{{ db_service }}"
      ansible.builtin.systemd:
        name: "{{ db_service }}"
        state: stopped
        enabled: false
      ignore_errors: yes
    
    - name: 패키지 삭제 - "{{ web_package }}", "{{ db_package }}"
      ansible.builtin.yum:
        name:
          - "{{ web_package }}"
          - "{{ db_package }}"
        state: absent
