---
- name: Restore playbook.yml
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks:
    #######################
    # 1) 방화벽 포트 제거
    # 2) 서비스 종료
    # 3) 서비스 설정 삭제
    # 4) 패키지 삭제
    #######################
    # 1) 방화벽 포트 제거
    - name: 1) 방화벽 포트 제거 - {{ open_service }}
      ansible.posix.firewalld:
        service: "{{ open_service }}"
        permanent: true
        immediate: true
        state: disabled

    # 2) 서비스 종료
    - name: 2) 서비스 종료 - {{ web_service }}, {{ firewall_service }}
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - "{{ web_service }}"
        - "{{ firewall_service }}"

    # 3) 서비스 설정 삭제
    # * /var/www/html/index.html
    - name: 3) 서비스 설정 삭제 - /var/www/html/index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    # 4) 패키지 삭제
    - name: 4) 패키지 삭제 - {{ web_pkg }}, {{ python_pkg }}
      ansible.builtin.dnf:
        name: 
          - "{{ web_pkg }}"
          - "{{ python_pkg }}"
        state: absent
