---
- name: 0) DB 서비스 기동 - loop test
  hosts: database_prod
  gather_facts: true
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
  tasks:
    ######################################
    # 1) 패키지 설치 - mariadb-server, python3-PyMySQL
    # 2) 서비스 기동 - mariadb
    ######################################
    - name: 1) 패키지 설치 - mariadb-server, python3-PyMySQL
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"
      when: ansible_distribution == 'RedHat'

    - name: 서비스 기동 - mariadb
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: started
        enabled: true
